[package]
name = "PicoOS"
version = "0.1.3"
edition = "2021"

[[bin]]
name = "PicoOS"
path = "src/main.rs"
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
selftest = []
task_bootstrap_test = []
task_stack_switch_test = []
sequential_task_test = []
task_yield_test = []
scheduler_skip_finished_test = []
scheduler_driven_task_test = []
resume_candidate_test = []
resume_preflight_test = []
resume_dry_run_test = []
resume_restore_test = []
real_resume_restore_test = []
real_resume_restore_jump = []
two_yield_task_test = []
scheduler_resume_loop_test = []
verbose_resume_debug = []
scheduler_dispatch_test = []

scheduler_dispatch_selftest = [
  "task_resume_selftest",
  "scheduler_dispatch_test",
]
task_resume_selftest = [
  "task_yield_test",
  "resume_candidate_test",
  "resume_preflight_test",
  "resume_dry_run_test",
  "resume_restore_test",
  "real_resume_restore_test",
  "real_resume_restore_jump",
  "two_yield_task_test",
  "scheduler_resume_loop_test",
]
